name: CI - Train models

on:
  push:
    branches:
      - kernelridge

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Decision Tree training
        run: python train.py --n_repeats 5 --test_size 0.2

      - name: Run KernelRidge training
        run: python train2.py --n_repeats 5 --test_size 0.2
